# Generated by Django 3.2 on 2022-07-15 04:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_change_site_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'zip', 'rar', '7z', 'gz', 'tar', 'bz2', 'bzip2', 'bz', 'bzip', 'bzp', 'bzt', 'bz2', 'bz3'])], verbose_name='file')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.assignment')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.entity')),
            ],
            options={
                'verbose_name': 'artifact',
                'verbose_name_plural': 'artifacts',
                'db_table': 'artifact',
            },
        ),
    ]
