# Generated by Django 3.2 on 2022-06-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_customuser_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
