# Generated by Django 3.2 on 2022-06-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_auto_20220621_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='userRole',
            field=models.TextField(choices=[('Student', 'Student'), ('Instructor', 'Instructor'), ('TA', 'Ta')], default='Student'),
        ),
    ]
