# Generated by Django 3.2 on 2022-06-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_registration_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='course_id'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='course name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='visible'),
        ),
    ]
