# Generated by Django 3.2 on 2022-07-15 08:09

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_alter_artifact_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='file',
            field=models.FileField(blank=True, upload_to='assignment_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'zip', 'rar', '7z', 'gz', 'tar', 'bz2', 'bzip2', 'bz', 'bzip', 'bzp', 'bzt', 'bz2', 'bz3', 'wbmp'])], verbose_name='assignment file'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='upload_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='upload time'),
        ),
    ]
