# Generated by Django 3.2 on 2022-06-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_auto_20220622_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=True, max_length=150, verbose_name='course_id')),
                ('assignment_name', models.CharField(blank=True, max_length=150, verbose_name='assignment name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('assignment_type', models.TextField(choices=[('Individual', 'Individual'), ('Team', 'Team')], default='Individual')),
                ('submission_type', models.TextField(choices=[('File', 'File'), ('URL', 'Url'), ('Text', 'Text')], default='File')),
                ('total_score', models.IntegerField(default=0, verbose_name='total score')),
                ('weight', models.IntegerField(default=0, verbose_name='weight')),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('date_released', models.DateTimeField(verbose_name='date released')),
                ('date_due', models.DateTimeField(verbose_name='date due')),
                ('review_assign_policy', models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'db_table': 'assignment',
            },
        ),
    ]
