# Generated by Django 3.2 on 2022-06-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.TextField(blank=True, choices=[('Individual', 'Individual'), ('Team', 'Team')], default='Individual'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_created',
            field=models.DateTimeField(blank=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_due',
            field=models.DateTimeField(blank=True, verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_released',
            field=models.DateTimeField(blank=True, verbose_name='date released'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='review_assign_policy',
            field=models.TextField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submission_type',
            field=models.TextField(blank=True, choices=[('File', 'File'), ('URL', 'Url'), ('Text', 'Text')], default='File'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='total_score',
            field=models.IntegerField(blank=True, default=0, verbose_name='total score'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='weight',
            field=models.IntegerField(blank=True, default=0, verbose_name='weight'),
        ),
    ]
