# Generated by Django 3.2 on 2022-10-01 22:54

import app.gamification.models.course
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_artifactreview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), app.gamification.models.course.FileSizeValidator(max_size=5242880)], verbose_name='course picture'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a PDF file.', upload_to='assignment_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='assignment file'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_due',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_released',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date released'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(blank=True, max_length=150, verbose_name='course number'),
        ),
    ]
