# Generated by Django 3.2 on 2022-06-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_auto_20220614_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
