# Generated by Django 3.2 on 2022-06-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_auto_20220626_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_created',
            field=models.DateTimeField(blank=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_due',
            field=models.DateTimeField(blank=True, verbose_name='date_due'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_released',
            field=models.DateTimeField(blank=True, verbose_name='date_released'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='total_score',
            field=models.IntegerField(blank=True, default=0, verbose_name='total_score'),
        ),
    ]
