# Generated by Django 3.2 on 2022-06-27 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_auto_20220626_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_due',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='date_due'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_released',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='date_released'),
        ),
    ]
