# Generated by Django 3.2 on 2022-11-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0009_auto_20221114_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number_of_scale',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.TextField(choices=[('MULTIPLETEXT', 'Multipletext'), ('FIXEDTEXT', 'Fixedtext'), ('MULTIPLECHOICE', 'Multiplechoice'), ('SLIDEREVIEW', 'Slidereview'), ('TEXTAREA', 'Textarea'), ('NUMBER', 'Number'), ('SCALEMULTIPLECHOICE', 'Scalemultiplechoice')], default='MULTIPLECHOICE'),
        ),
    ]
