# Generated by Django 3.2 on 2022-12-05 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0010_auto_20221124_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraint',
            name='description',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='rule',
        ),
        migrations.AddField(
            model_name='constraint',
            name='url',
            field=models.TextField(blank=True, verbose_name='url'),
        ),
        migrations.CreateModel(
            name='RuleConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.constraint')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.rule')),
            ],
            options={
                'verbose_name': 'rule constraint',
                'verbose_name_plural': 'rule constraints',
                'db_table': 'rule_constraints',
            },
        ),
    ]
