# Generated by Django 3.2 on 2022-12-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0011_auto_20221205_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraint',
            name='met',
        ),
        migrations.AddField(
            model_name='progress',
            name='met',
            field=models.BooleanField(default=False),
        ),
    ]
